name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.templates.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List templates
        id: templates
        run: echo "matrix=$(ls templates/*.pkr.hcl | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: list
    strategy:
      fail-fast: true
      matrix:
        template: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup os
        run: sudo apt-get install qemu-user-static -y
      - name: Setup env
        run: echo "$(echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[]|select(.key|contains("PKR_VAR"))|"\(.key[:8])\(.key[8:]|ascii_downcase)=\(.value)"')" >> $GITHUB_ENV
      - name: Setup packer
        uses: hashicorp/setup-packer@v2.0.1
        with:
          version: 1.8.5
      - name: Install dependencies
        run: packer init config.pkr.hcl
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
      - name: Run build
        run: sudo -E packer build ${{ matrix.template }}
      - name: Locate artifact
        id: locate
        run: echo "artifact=$(ls *.img)" >> $GITHUB_OUTPUT
        working-directory: build
      - name: Compress artifact
        run: sudo bash -c "xz -f -z -9 -T 2 ${{ steps.locate.outputs.artifact }}"
        working-directory: build
      - name: Checksum artifact
        run: sudo bash -c "sha256sum ${{ steps.locate.outputs.artifact }}.xz > ${{ steps.locate.outputs.artifact }}.xz.sha256"
        working-directory: build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build
  release:
    runs-on: ubuntu-latest
    needs: [list, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
