name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.templates.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List templates
        id: templates
        run: echo "matrix=$(ls templates/*.pkr.hcl | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-latest
    needs: list
    strategy:
      fail-fast: true
      matrix:
        template: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup os
        run: sudo apt-get install qemu-user-static -y
      - name: Setup env
        run: echo "$(echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[]|select(.key|contains("PKR_VAR"))|"\(.key[:8])\(.key[8:]|ascii_downcase)=\(.value)"')" >> $GITHUB_ENV
      - name: Setup packer
        uses: hashicorp/setup-packer@v2.0.1
        with:
          version: 1.8.5
      - name: Install dependencies
        run: packer init config.pkr.hcl
        env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.PACKER_GITHUB_API_TOKEN }}
      - name: Run lint
        run: packer validate ${{ matrix.template }}
      - name: Run build
        run: sudo -E packer build ${{ matrix.template }}
